# Generated by Django 5.2.16 on 2026-08-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
    ]
