# Generated by Django 5.2.16 on 2026-08-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('name', models.EmailField(max_length=255)),
            ],
        ),
    ]
